### ISSUE TITLE
Readability Issues with the extension.

### ISSUE THREAD

**Issue by simar7** [sourcegraph/sourcegraph-browser-extensions#13]
Hello,

I've been using the chrome extension and so far it works really well! One thing I've noticed is the lack of contrast in the text that pops up for code snippets. Below is an example:

![screen shot 2016-10-11 at 12 52 09 am](https://cloud.githubusercontent.com/assets/1254783/19262676/2e6f9594-8f4d-11e6-8706-b8cbdf44e4b3.png)

I'm willing to look into (and submit a PR) for this if it's an easy fix and is currently not being worked on. However the link to the actual source code repo seems to be broken (in the README): https://sourcegraph.com/sourcegraph/sourcegraph@master/-/tree/client/browser-ext/chrome

**Comment by uforic** [comment]
Hey @simar7,

Thanks for filing this, and for the screenshot - I see you are using a plugin that changes the background of GitHub, I'm guessing that we have an opaque setting that is optimized for white backgrounds. Who makes that plugin? Can install it myself and make sure we fix it for that use case.

Also, the source code for the extension is no longer public, so I'll update the README. Thanks for pointing that out.

-Matt

**Comment by simar7** [comment]
Hello @uforic,

The following are the steps to reproduce:

1) Install [stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) for Chrome.
2) Grab the [GitHub Dark](https://userstyles.org/styles/37035/github-dark) extension for stylish.
3) Install the Sourcegraph plugin and see the output.

Thank you for supporting this, definitely appreciate your help!

**Comment by uforic** [comment]
Hey @simar7 , I was able to get a repro with the above steps, and have pushed a fix to our code base. We release our chrome extension pretty frequently, I expect you'll see the result within the next day or two.

Was fixed with a simple: `color: black`, the GitHub dark theme was overriding the default font color.

Thanks for reporting! Also, have you checked out the new Sourcegraph UI yet? Head over to https://sourcegraph.com/github.com/docker/docker@master/-/blob/cmd/docker/docker.go to check it out. You can navigate to any repo on GitHub using the search bar, and we even have jump to def and jump to file. We're hoping it'll be a great way to go code spellunking, let us know what you think!
